#!/bin/bash
# YouTube 字幕轉換器 - Mac App 啟動器

SCRIPT_PATH="$HOME/ai_class_flywheel/tools/youtube_subtitle_converter/YouTube字幕轉換器.app/Contents/Resources/start.sh"

osascript -e "tell application \"Terminal\" to do script \"bash '$SCRIPT_PATH'\""
osascript -e "tell application \"Terminal\" to activate"
