# YouTube 字幕轉換器 - Cloud Build 自動部署設定
#
# 使用方式：
# gcloud builds submit --config cloudbuild.yaml

steps:
  # 建構 Docker 映像
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/youtube-subtitle-converter'
      - '.'

  # 推送映像到 Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/youtube-subtitle-converter'

  # 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'youtube-subtitle-converter'
      - '--image'
      - 'gcr.io/$PROJECT_ID/youtube-subtitle-converter'
      - '--region'
      - 'asia-east1'  # 台灣區域
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '900'  # 15 分鐘，處理長影片需要時間
      - '--concurrency'
      - '10'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'

images:
  - 'gcr.io/$PROJECT_ID/youtube-subtitle-converter'

timeout: '1800s'  # 建構超時 30 分鐘
